name: SparkLabs
favicon: null
layout_spectrum: 0.10791005287319422
typography_spectrum: 0.7320488521363586
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.6044101410079747
  lightness: 0.4169012433849275
  saturation: 0.19383109314367175
  rhythmicContrast: 0.7368304766714573
purpose: []
